[2021-05-13 14:47:14,690] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: CS_GO_Pipeline.Matches_Crawler 2021-05-12T00:00:00+00:00 [queued]>
[2021-05-13 14:47:14,705] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: CS_GO_Pipeline.Matches_Crawler 2021-05-12T00:00:00+00:00 [queued]>
[2021-05-13 14:47:14,705] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-13 14:47:14,705] {taskinstance.py:1069} INFO - Starting attempt 1 of 4
[2021-05-13 14:47:14,706] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-13 14:47:14,714] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): Matches_Crawler> on 2021-05-12T00:00:00+00:00
[2021-05-13 14:47:14,717] {standard_task_runner.py:52} INFO - Started process 47 to run task
[2021-05-13 14:47:14,720] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'CS_GO_Pipeline', 'Matches_Crawler', '2021-05-12T00:00:00+00:00', '--job-id', '4', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/csgo_pipeline.py', '--cfg-path', '/tmp/tmpkwih4scc', '--error-file', '/tmp/tmpklwt1c8b']
[2021-05-13 14:47:14,721] {standard_task_runner.py:77} INFO - Job 4: Subtask Matches_Crawler
[2021-05-13 14:47:14,759] {logging_mixin.py:104} INFO - Running <TaskInstance: CS_GO_Pipeline.Matches_Crawler 2021-05-12T00:00:00+00:00 [running]> on host 834203160f1c
[2021-05-13 14:47:14,796] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Filipe
AIRFLOW_CTX_DAG_ID=CS_GO_Pipeline
AIRFLOW_CTX_TASK_ID=Matches_Crawler
AIRFLOW_CTX_EXECUTION_DATE=2021-05-12T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2021-05-12T00:00:00+00:00
[2021-05-13 14:47:14,796] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-05-13 14:47:14,797] {bash.py:158} INFO - Running command: cd /opt && scrapy runspider results_scrapy.py -o teste.json
[2021-05-13 14:47:14,803] {bash.py:169} INFO - Output:
[2021-05-13 14:47:14,805] {bash.py:173} INFO - bash: scrapy: command not found
[2021-05-13 14:47:14,805] {bash.py:177} INFO - Command exited with return code 127
[2021-05-13 14:47:14,815] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-05-13 14:47:14,817] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=CS_GO_Pipeline, task_id=Matches_Crawler, execution_date=20210512T000000, start_date=20210513T144714, end_date=20210513T144714
[2021-05-13 14:47:14,854] {local_task_job.py:146} INFO - Task exited with return code 1
