[2021-05-13 14:55:37,481] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: CS_GO_Pipeline.Matches_Crawler 2021-05-13T14:55:36.314544+00:00 [queued]>
[2021-05-13 14:55:37,496] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: CS_GO_Pipeline.Matches_Crawler 2021-05-13T14:55:36.314544+00:00 [queued]>
[2021-05-13 14:55:37,496] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-13 14:55:37,496] {taskinstance.py:1069} INFO - Starting attempt 1 of 4
[2021-05-13 14:55:37,497] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-13 14:55:37,505] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): Matches_Crawler> on 2021-05-13T14:55:36.314544+00:00
[2021-05-13 14:55:37,508] {standard_task_runner.py:52} INFO - Started process 85 to run task
[2021-05-13 14:55:37,512] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'CS_GO_Pipeline', 'Matches_Crawler', '2021-05-13T14:55:36.314544+00:00', '--job-id', '9', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/csgo_pipeline.py', '--cfg-path', '/tmp/tmpjqi9mpev', '--error-file', '/tmp/tmpf2pcuhgq']
[2021-05-13 14:55:37,512] {standard_task_runner.py:77} INFO - Job 9: Subtask Matches_Crawler
[2021-05-13 14:55:37,550] {logging_mixin.py:104} INFO - Running <TaskInstance: CS_GO_Pipeline.Matches_Crawler 2021-05-13T14:55:36.314544+00:00 [running]> on host 834203160f1c
[2021-05-13 14:55:37,655] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Filipe
AIRFLOW_CTX_DAG_ID=CS_GO_Pipeline
AIRFLOW_CTX_TASK_ID=Matches_Crawler
AIRFLOW_CTX_EXECUTION_DATE=2021-05-13T14:55:36.314544+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-05-13T14:55:36.314544+00:00
[2021-05-13 14:55:37,656] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-05-13 14:55:37,657] {bash.py:158} INFO - Running command: cd /opt/airflow/logs/CS_GO_Pipeline && scrapy runspider results_scrapy.py -o teste.json
[2021-05-13 14:55:37,664] {bash.py:169} INFO - Output:
[2021-05-13 14:55:38,569] {bash.py:173} INFO - 2021-05-13 14:55:38 [scrapy.utils.log] INFO: Scrapy 2.5.0 started (bot: scrapybot)
[2021-05-13 14:55:38,574] {bash.py:173} INFO - 2021-05-13 14:55:38 [scrapy.utils.log] INFO: Versions: lxml 4.6.3.0, libxml2 2.9.10, cssselect 1.1.0, parsel 1.6.0, w3lib 1.22.0, Twisted 21.2.0, Python 3.6.13 (default, Mar 27 2021, 03:29:33) - [GCC 8.3.0], pyOpenSSL 19.1.0 (OpenSSL 1.1.1k  25 Mar 2021), cryptography 3.4.7, Platform Linux-5.4.72-microsoft-standard-WSL2-x86_64-with-debian-10.8
[2021-05-13 14:55:38,574] {bash.py:173} INFO - 2021-05-13 14:55:38 [scrapy.utils.log] DEBUG: Using reactor: twisted.internet.epollreactor.EPollReactor
[2021-05-13 14:55:38,574] {bash.py:173} INFO - Usage
[2021-05-13 14:55:38,575] {bash.py:173} INFO - =====
[2021-05-13 14:55:38,575] {bash.py:173} INFO -   scrapy runspider [options] <spider_file>
[2021-05-13 14:55:38,575] {bash.py:173} INFO - 
[2021-05-13 14:55:38,576] {bash.py:173} INFO - runspider: error: File not found: results_scrapy.py
[2021-05-13 14:55:38,576] {bash.py:173} INFO - 
[2021-05-13 14:55:38,648] {bash.py:177} INFO - Command exited with return code 2
[2021-05-13 14:55:38,658] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-05-13 14:55:38,660] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=CS_GO_Pipeline, task_id=Matches_Crawler, execution_date=20210513T145536, start_date=20210513T145537, end_date=20210513T145538
[2021-05-13 14:55:38,769] {local_task_job.py:146} INFO - Task exited with return code 1
