[2021-05-13 15:08:49,942] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: CS_GO_Pipeline.Matches_Crawler 2021-05-13T14:58:45.328604+00:00 [queued]>
[2021-05-13 15:08:49,970] {taskinstance.py:877} INFO - Dependencies all met for <TaskInstance: CS_GO_Pipeline.Matches_Crawler 2021-05-13T14:58:45.328604+00:00 [queued]>
[2021-05-13 15:08:49,970] {taskinstance.py:1068} INFO - 
--------------------------------------------------------------------------------
[2021-05-13 15:08:49,970] {taskinstance.py:1069} INFO - Starting attempt 3 of 4
[2021-05-13 15:08:49,971] {taskinstance.py:1070} INFO - 
--------------------------------------------------------------------------------
[2021-05-13 15:08:49,988] {taskinstance.py:1089} INFO - Executing <Task(BashOperator): Matches_Crawler> on 2021-05-13T14:58:45.328604+00:00
[2021-05-13 15:08:49,992] {standard_task_runner.py:52} INFO - Started process 101 to run task
[2021-05-13 15:08:49,995] {standard_task_runner.py:76} INFO - Running: ['airflow', 'tasks', 'run', 'CS_GO_Pipeline', 'Matches_Crawler', '2021-05-13T14:58:45.328604+00:00', '--job-id', '13', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/csgo_pipeline.py', '--cfg-path', '/tmp/tmpa8f8o4hl', '--error-file', '/tmp/tmpj7_w14fg']
[2021-05-13 15:08:49,996] {standard_task_runner.py:77} INFO - Job 13: Subtask Matches_Crawler
[2021-05-13 15:08:50,037] {logging_mixin.py:104} INFO - Running <TaskInstance: CS_GO_Pipeline.Matches_Crawler 2021-05-13T14:58:45.328604+00:00 [running]> on host 834203160f1c
[2021-05-13 15:08:50,065] {taskinstance.py:1283} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=Filipe
AIRFLOW_CTX_DAG_ID=CS_GO_Pipeline
AIRFLOW_CTX_TASK_ID=Matches_Crawler
AIRFLOW_CTX_EXECUTION_DATE=2021-05-13T14:58:45.328604+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2021-05-13T14:58:45.328604+00:00
[2021-05-13 15:08:50,066] {bash.py:135} INFO - Tmp dir root location: 
 /tmp
[2021-05-13 15:08:50,067] {bash.py:158} INFO - Running command: cd /opt/airflow/CS_GO_Pipeline && ls
[2021-05-13 15:08:50,073] {bash.py:169} INFO - Output:
[2021-05-13 15:08:50,074] {bash.py:173} INFO - bash: line 0: cd: /opt/airflow/CS_GO_Pipeline: No such file or directory
[2021-05-13 15:08:50,074] {bash.py:177} INFO - Command exited with return code 1
[2021-05-13 15:08:50,085] {taskinstance.py:1482} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1138, in _run_raw_task
    self._prepare_and_execute_task_with_callbacks(context, task)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1311, in _prepare_and_execute_task_with_callbacks
    result = self._execute_task(context, task_copy)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/models/taskinstance.py", line 1341, in _execute_task
    result = task_copy.execute(context=context)
  File "/home/airflow/.local/lib/python3.6/site-packages/airflow/operators/bash.py", line 180, in execute
    raise AirflowException('Bash command failed. The command returned a non-zero exit code.')
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code.
[2021-05-13 15:08:50,086] {taskinstance.py:1532} INFO - Marking task as UP_FOR_RETRY. dag_id=CS_GO_Pipeline, task_id=Matches_Crawler, execution_date=20210513T145845, start_date=20210513T150849, end_date=20210513T150850
[2021-05-13 15:08:50,129] {local_task_job.py:146} INFO - Task exited with return code 1
